apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex
    app.kubernetes.io/part-of: rh-trex
  name: rh-trex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/rh-trex/rh-trex@sha256:66c8c6bff2c7c2c5f0a88e2f614a183d23aa0b990518e13b5f7c84d088b0f671
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
