apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/rh-trex/rh-trex@sha256:66c8c6bff2c7c2c5f0a88e2f614a183d23aa0b990518e13b5f7c84d088b0f671
        name: container-image
        resources: {}
status: {}
