apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/rh-trex/rh-trex@sha256:2b20b6717182f349f567facce92dcdb412fabd1d6f1a8831bb4542b16defd5f8
        name: container-image
        resources: {}
status: {}
