apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/rh-trex/rh-trex@sha256:cc093544e7cfc449efd1f92c3b66966680ee68faf2d770ebf38850d11634b4a7
        name: container-image
        resources: {}
status: {}
